import crypto from "node:crypto"

export type GeneratedCoverImage = {
  url: string | null
  path: string | null
  prompt: string
}

export async function generateBlogCoverImage(params: {
  title: string
  excerpt?: string | null
  versionId: string
}): Promise<GeneratedCoverImage | null> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey) return null

  // Non-blocking placeholder implementation:
  // If Gemini image generation is configured later, this helper can be expanded
  // to upload generated bytes into Supabase Storage and return public URL/path.
  const prompt = `Editorial blog cover illustration for: ${params.title}. Context: ${params.excerpt ?? ""}`.trim()

  // deterministic pseudo-path for future uploads; keeps audit trail predictable
  const hash = crypto.createHash("sha1").update(`${params.versionId}:${prompt}`).digest("hex").slice(0, 12)
  return {
    url: null,
    path: `blog/covers/${hash}.png`,
    prompt,
  }
}
